(()=>{'use strict';
const colors=window.MIATA_COLORS,tiers=[['s','S','#ef5350'],['a','A','#ff9f43'],['b','B','#ffd166'],['c','C','#72c68b'],['d','D','#68a9df']];
const nonUsOnly=new Set(['na-excellent-green','na-sparkle-green','na-platinum-pearl','nb-cerrion-silver','nb-platinum-pearl','nc-metropolitan-gray','nc-titanium-flash','nc-deep-crystal-blue','nc-aurora-blue','nc-aquatic-blue','nc-spirited-green','nc-competition-yellow','nc-radiant-ebony']);
const generationYears={NA:'1989-1997',NB:'1998-2005',NC:'2006-2015',ND:'2015-present'},photoIndexes=[0,1,2,3];
const state={placements:{},generation:'ALL',region:'WORLD',search:''};let active=null,photo=0,dragged=null,photoSources={},dragY=null,scrollFrame=null;
const $=s=>document.querySelector(s),board=$('#board'),catalog=$('#catalog'),viewer=$('#viewer');
function query(c){const year=c.years.match(/\d{4}/)?.[0]||'';return `${year} Mazda MX-5 Miata ${c.generation} ${c.name} factory color`;}
function photoUrl(c,i=0){return `assets/photos/${c.id}/${i}.jpg`;}
function sourceUrl(c){return photoSources[c.id]?.[photo]?.sourcePage||`https://www.bing.com/images/search?q=${encodeURIComponent(query(c))}`;}
function stopDragScroll(){dragY=null;if(scrollFrame)cancelAnimationFrame(scrollFrame);scrollFrame=null;}
function dragScroll(){if(!dragged||dragY===null){stopDragScroll();return;}const edge=Math.min(150,innerHeight*.22);let speed=0;if(dragY<edge)speed=-Math.pow((edge-dragY)/edge,2)*24;else if(dragY>innerHeight-edge)speed=Math.pow((dragY-(innerHeight-edge))/edge,2)*24;if(speed)scrollBy(0,speed);scrollFrame=requestAnimationFrame(dragScroll);}
function makeCard(c){const el=document.createElement('article');el.className='card';el.dataset.id=c.id;el.draggable=true;el.tabIndex=0;el.setAttribute('aria-label',`${c.generation} ${c.name}, ${c.years}, paint code ${c.code}. Open details.`);el.innerHTML=`<div class="photo"><img src="${photoUrl(c,0,480,300)}" alt="${c.name} ${c.generation} Mazda MX-5" loading="lazy" draggable="false"><i>${c.generation}</i></div><div class="label"><strong>${c.name}</strong><div><span>${c.years}</span><span>${c.code}</span></div></div>`;el.onclick=()=>open(c);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(c);}};el.ondragstart=e=>{dragged=c.id;dragY=e.clientY;el.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',c.id);scrollFrame=requestAnimationFrame(dragScroll);};el.ondragend=()=>{dragged=null;stopDragScroll();el.classList.remove('dragging');document.querySelectorAll('.over').forEach(x=>x.classList.remove('over'));};return el;}
function dropZone(el,tier){el.ondragover=e=>{e.preventDefault();el.classList.add('over');};el.ondragleave=()=>el.classList.remove('over');el.ondrop=e=>{e.preventDefault();el.classList.remove('over');place(e.dataTransfer.getData('text/plain')||dragged,tier);};}
function segmented(root,options,selected,onSelect){options.forEach(([value,label])=>{const b=document.createElement('button');b.textContent=label;b.className=value===selected?'active':'';b.onclick=()=>{onSelect(value);root.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render();};root.append(b);});}
function build(){tiers.forEach(([id,label,color])=>{const row=document.createElement('div');row.className='tier';row.innerHTML=`<div class="tier-name" style="--color:${color}">${label}</div><div class="drop" data-tier="${id}" aria-label="Tier ${label}"></div>`;dropZone(row.lastElementChild,id);board.append(row);$('#tierSelect').add(new Option(`Tier ${label}`,id));});dropZone(catalog,'unranked');segmented($('#filters'),[['ALL','All'],['NA','NA'],['NB','NB'],['NC','NC'],['ND','ND']],state.generation,v=>state.generation=v);segmented($('#regionFilters'),[['WORLD','Worldwide'],['US','U.S. only']],state.region,v=>state.region=v);}
function matches(c,needle){return(state.generation==='ALL'||c.generation===state.generation)&&(state.region==='WORLD'||!nonUsOnly.has(c.id))&&(!needle||`${c.name} ${c.code} ${c.years} ${c.note}`.toLowerCase().includes(needle));}
function generationGroup(g,items){const section=document.createElement('section');section.className='generation-group';section.innerHTML=`<div class="generation-heading"><div><b>${g}</b><span>${generationYears[g]}</span></div><small>${items.length} color${items.length===1?'':'s'}</small></div><div class="catalog-grid"></div>`;items.forEach(c=>section.lastElementChild.append(makeCard(c)));return section;}
function render(){document.querySelectorAll('.drop').forEach(z=>z.replaceChildren());catalog.replaceChildren();const needle=state.search.trim().toLowerCase(),visible=[];colors.forEach(c=>{const tier=state.placements[c.id];if(tier){$(`[data-tier="${tier}"]`)?.append(makeCard(c));return;}if(matches(c,needle))visible.push(c);});['NA','NB','NC','ND'].forEach(g=>{const items=visible.filter(c=>c.generation===g);if(items.length)catalog.append(generationGroup(g,items));});$('#count').textContent=`${Object.keys(state.placements).length} ranked · ${visible.length} shown · ${colors.length} total`;$('#empty').hidden=visible.length>0;}
function place(id,tier){if(!id)return;if(tier==='unranked')delete state.placements[id];else state.placements[id]=tier;writeUrl();render();if(active?.id===id)$('#tierSelect').value=tier;}
function writeUrl(){const tierDigits=['','s','a','b','c','d'],ranking=colors.map(c=>Math.max(0,tierDigits.indexOf(state.placements[c.id]||''))).join('');history.replaceState(null,'',`${location.pathname}${location.search}#v=2&r=${ranking}`);}
function readUrl(){const p=new URLSearchParams(location.hash.slice(1));if(p.get('v')==='2'&&p.has('r')){const tierDigits=['','s','a','b','c','d'];[...p.get('r')].slice(0,colors.length).forEach((digit,i)=>{const tier=tierDigits[Number(digit)];if(tier)state.placements[colors[i].id]=tier;});return;}tiers.forEach(([tier])=>(p.get(tier)||'').split('.').filter(Boolean).forEach(id=>{if(colors.some(c=>c.id===id))state.placements[id]=tier;}));}
function open(c){active=c;photo=0;$('#generation').textContent=`${c.generation} generation`;$('#name').textContent=c.name;$('#code').textContent=c.code;$('#years').textContent=c.years;$('#note').textContent=c.note;$('#tierSelect').value=state.placements[c.id]||'unranked';$('#source').href=sourceUrl(c);showPhoto();viewer.showModal();}
function showPhoto(){const img=$('#largePhoto');img.src=photoUrl(active,photo);img.alt=`${active.name} ${active.generation} Mazda MX-5, photo ${photo+1}`;$('#source').href=sourceUrl(active);$('#dots').innerHTML=photoIndexes.map(i=>`<button class="${i===photo?'active':''}" data-i="${i}" aria-label="View photo ${i+1}"></button>`).join('');$('#dots').querySelectorAll('button').forEach(b=>b.onclick=()=>{photo=+b.dataset.i;showPhoto();});}
function shift(n){photo=(photo+n+4)%4;showPhoto();}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),2200);}
fetch('assets/photos/manifest.json').then(response=>response.json()).then(data=>{photoSources=data;if(active)$('#source').href=sourceUrl(active);}).catch(()=>{});build();readUrl();render();document.addEventListener('dragover',e=>{if(dragged)dragY=e.clientY;},{passive:true});document.addEventListener('drop',stopDragScroll);$('#search').oninput=e=>{state.search=e.target.value;render();};$('#tierSelect').onchange=e=>place(active.id,e.target.value);$('#close').onclick=()=>viewer.close();$('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);viewer.onclick=e=>{if(e.target===viewer)viewer.close();};viewer.onkeydown=e=>{if(e.key==='ArrowLeft')shift(-1);if(e.key==='ArrowRight')shift(1);};$('#share').onclick=async()=>{writeUrl();try{await navigator.clipboard.writeText(location.href);toast('Share link copied');}catch{toast('Copy the URL from your browser');}};$('#reset').onclick=()=>{if(!Object.keys(state.placements).length||confirm('Reset every ranked color?')){state.placements={};writeUrl();render();toast('Tier list reset');}};window.onhashchange=()=>{state.placements={};readUrl();render();};
})();
