(()=>{'use strict';
const colors=window.MIATA_COLORS,tiers=[['s','S','#ef5350'],['a','A','#ff9f43'],['b','B','#ffd166'],['c','C','#72c68b'],['d','D','#68a9df']];
const state={placements:{},generation:'ALL',search:''};let active=null,photo=0,dragged=null;
const $=s=>document.querySelector(s),board=$('#board'),catalog=$('#catalog'),viewer=$('#viewer');
function query(c){const year=c.years.match(/\d{4}/)?.[0]||'';return `${year} Mazda MX-5 Miata ${c.generation} ${c.name} factory color front three quarter`;}
function photoUrl(c,i=0,w=900,h=560){return `https://tse${i%4+1}.mm.bing.net/th?q=${encodeURIComponent(query(c))}&w=${w}&h=${h}&c=7&rs=1&p=${i}`;}
function sourceUrl(c){return `https://www.bing.com/images/search?q=${encodeURIComponent(query(c))}`;}
function makeCard(c){const el=document.createElement('article');el.className='card';el.dataset.id=c.id;el.draggable=true;el.tabIndex=0;el.setAttribute('aria-label',`${c.generation} ${c.name}, paint code ${c.code}. Open details.`);el.innerHTML=`<div class="photo"><img src="${photoUrl(c,0,480,300)}" alt="${c.name} ${c.generation} Mazda MX-5" loading="lazy" draggable="false"><i>${c.generation}</i></div><div class="label"><strong>${c.name}</strong><span>${c.code}</span></div>`;el.onclick=()=>open(c);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(c);}};el.ondragstart=e=>{dragged=c.id;el.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',c.id);};el.ondragend=()=>{dragged=null;el.classList.remove('dragging');};return el;}
function dropZone(el,tier){el.ondragover=e=>{e.preventDefault();el.classList.add('over');};el.ondragleave=()=>el.classList.remove('over');el.ondrop=e=>{e.preventDefault();el.classList.remove('over');place(e.dataTransfer.getData('text/plain')||dragged,tier);};}
function build(){tiers.forEach(([id,label,color])=>{const row=document.createElement('div');row.className='tier';row.innerHTML=`<div class="tier-name" style="--color:${color}">${label}</div><div class="drop" data-tier="${id}" aria-label="Tier ${label}"></div>`;dropZone(row.lastElementChild,id);board.append(row);$('#tierSelect').add(new Option(`Tier ${label}`,id));});dropZone(catalog,'unranked');['ALL','NA','NB','NC','ND'].forEach(g=>{const b=document.createElement('button');b.textContent=g==='ALL'?'All':g;b.className=g==='ALL'?'active':'';b.onclick=()=>{state.generation=g;$('#filters').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render();};$('#filters').append(b);});}
function render(){document.querySelectorAll('.drop').forEach(z=>z.replaceChildren());catalog.replaceChildren();const needle=state.search.trim().toLowerCase();let shown=0;colors.forEach(c=>{const tier=state.placements[c.id];if(tier){$(`[data-tier="${tier}"]`)?.append(makeCard(c));return;}if((state.generation==='ALL'||c.generation===state.generation)&&(!needle||`${c.name} ${c.code} ${c.note}`.toLowerCase().includes(needle))){catalog.append(makeCard(c));shown++;}});$('#count').textContent=`${Object.keys(state.placements).length} ranked · ${shown} shown · ${colors.length} total`;$('#empty').hidden=shown>0;}
function place(id,tier){if(!id)return;if(tier==='unranked')delete state.placements[id];else state.placements[id]=tier;writeUrl();render();if(active?.id===id)$('#tierSelect').value=tier;}
function writeUrl(){const p=new URLSearchParams({v:'1'});tiers.forEach(([id])=>{const ids=colors.filter(c=>state.placements[c.id]===id).map(c=>c.id);if(ids.length)p.set(id,ids.join('.'));});history.replaceState(null,'',`${location.pathname}${location.search}#${p}`);}
function readUrl(){const p=new URLSearchParams(location.hash.slice(1));tiers.forEach(([tier])=>(p.get(tier)||'').split('.').filter(Boolean).forEach(id=>{if(colors.some(c=>c.id===id))state.placements[id]=tier;}));}
function open(c){active=c;photo=0;$('#generation').textContent=`${c.generation} generation`;$('#name').textContent=c.name;$('#code').textContent=c.code;$('#years').textContent=c.years;$('#note').textContent=c.note;$('#tierSelect').value=state.placements[c.id]||'unranked';$('#source').href=sourceUrl(c);showPhoto();viewer.showModal();}
function showPhoto(){const img=$('#largePhoto');img.src=photoUrl(active,photo);img.alt=`${active.name} ${active.generation} Mazda MX-5, view ${photo+1}`;$('#dots').innerHTML=[0,1,2,3].map(i=>`<button class="${i===photo?'active':''}" data-i="${i}" aria-label="View photo ${i+1}"></button>`).join('');$('#dots').querySelectorAll('button').forEach(b=>b.onclick=()=>{photo=+b.dataset.i;showPhoto();});}
function shift(n){photo=(photo+n+4)%4;showPhoto();}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),2200);}
build();readUrl();render();$('#search').oninput=e=>{state.search=e.target.value;render();};$('#tierSelect').onchange=e=>place(active.id,e.target.value);$('#close').onclick=()=>viewer.close();$('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);viewer.onclick=e=>{if(e.target===viewer)viewer.close();};viewer.onkeydown=e=>{if(e.key==='ArrowLeft')shift(-1);if(e.key==='ArrowRight')shift(1);};$('#share').onclick=async()=>{writeUrl();try{await navigator.clipboard.writeText(location.href);toast('Share link copied');}catch{toast('Copy the URL from your browser');}};$('#reset').onclick=()=>{if(!Object.keys(state.placements).length||confirm('Reset every ranked color?')){state.placements={};writeUrl();render();toast('Tier list reset');}};window.onhashchange=()=>{state.placements={};readUrl();render();};
})();
